name: Build
on: [push, pull_request]

jobs:
  build-all:
    strategy:
      matrix:
        java: [8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initalize git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "Github CI"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Fetch paper commit
        id: paper-version
        run: echo "::set-output name=commit::$(git rev-parse @:./Paper)"
      - uses: actions/cache@v1
        name: Cache paper
        id: cache-paper
        with:
          path: Paper
          key: ${{ runner.os }}-paper-${{ steps.paper-version.outputs.commit }}
      - name: Setup paper
        if: steps.cache-paper.outputs.cache-hit != 'true'
        run: ./gradlew paperInit
      - name: Setup workspace
        run: ./gradlew paperApplyPatches
      - uses: actions/cache@v1
        name: Cache gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        name: Cache maven
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Gradle
        id: build
        run: ./gradlew jar sourcesJar javadocJar shadowJar paperclip
      - name: Upload API Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ibento-api
          path: Ibento-API/build/libs/
      - name: Upload Paperclip Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ibento-paperclip
          path: ibento-paperclip.jar
